import {afterEach,describe,it,expect,vi} from 'vitest';
const MAIN='000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f',TEST='00000000da84f2bafbbc53dee25a72ae507ff4914b867c565be350b0da8bf043';
afterEach(()=>{vi.resetModules();vi.doUnmock('../src/lib/network');});
async function load(network:'mainnet'|'testnet4'){vi.resetModules();vi.doMock('../src/lib/network',async()=>{const btc=await import('@scure/btc-signer');return{NETWORK_ID:network,BITCOIN_NETWORK:network==='mainnet'?btc.NETWORK:btc.TEST_NETWORK,NETWORK_CONFIG:{chainUrl:'https://example.invalid',minerUrl:'https://example.invalid',genesisHash:network==='mainnet'?MAIN:TEST}}});return import('../server/chain');}
describe.each(['mainnet','testnet4'] as const)('%s configured chain identity',network=>{
 it('checks exact genesis and keeps checking after success',async()=>{const{Esplora}=await load(network),request=vi.fn().mockResolvedValueOnce(new Response(' '+(network==='mainnet'?MAIN:TEST)+'\n')).mockResolvedValueOnce(new Response(network==='mainnet'?TEST:MAIN)),c=new Esplora('https://example.invalid',request);await expect(c.assertNetwork()).resolves.toBeUndefined();await expect(c.assertNetwork()).rejects.toThrow('not Bitcoin '+network);expect(request.mock.calls.map(x=>String(x[0]))).toEqual(['https://example.invalid/block-height/0','https://example.invalid/block-height/0']);});
 for(const op of ['raw','status','unspent','paymentUtxos'] as const)it('wrong genesis prevents '+op+' data lookup',async()=>{const{Esplora}=await load(network),request=vi.fn().mockResolvedValue(new Response(network==='mainnet'?TEST:MAIN)),c=new Esplora('https://example.invalid',request);const p={txid:'11'.repeat(32),vout:0,value:'1000'};const result=op==='unspent'?c.unspent(p,'51'):op==='paymentUtxos'?c.paymentUtxos('not reached'):c[op](p.txid);await expect(result).rejects.toThrow('not Bitcoin '+network);expect(request).toHaveBeenCalledTimes(1);expect(new URL(String(request.mock.calls[0][0])).pathname).toBe('/block-height/0');});
 it('HTTP and transport failures fail closed without a status lookup',async()=>{const{Esplora}=await load(network);for(const request of [vi.fn().mockResolvedValue(new Response('unavailable',{status:503})),vi.fn().mockRejectedValue(new TypeError('transport'))]){const c=new Esplora('https://example.invalid',request);await expect(c.status('11'.repeat(32))).rejects.toThrow();expect(request).toHaveBeenCalledTimes(1);}});
 it('correct genesis permits subsequent unconfirmed status read in order',async()=>{const{Esplora}=await load(network),request=vi.fn().mockResolvedValueOnce(new Response(network==='mainnet'?MAIN:TEST)).mockResolvedValueOnce(Response.json({confirmed:false})),c=new Esplora('https://example.invalid',request);await expect(c.status('11'.repeat(32))).resolves.toEqual({confirmed:false,confirmations:0});expect(request.mock.calls.map(x=>new URL(String(x[0])).pathname)).toEqual(['/block-height/0','/tx/'+ '11'.repeat(32)+'/status']);});
});
