import { test, expect } from "@playwright/test";
test("costs distinguish illustrations, unavailable charges and stale rates", async ({ page }) => {
  let unavailable = false;
  await page.route("**/api/rates", route => route.fulfill({status: unavailable ? 503 : 200, contentType: "application/json", body: JSON.stringify(unavailable ? {error: "Unavailable"} : {effective_rate: 4, submit_fee_rate: 1})}));
  await page.goto("/");
  await page.getByRole("button", {name: "Costs & billing"}).click();
  await expect(page.getByRole("heading", {name: "Every cost, explained."})).toBeVisible();
  await expect(page.getByRole("region", {name:"Itemized costs"}).getByText("Customer billing is not enabled.", {exact:true})).toBeVisible();
  await expect(page.getByRole("button", {name: /Authorize compute budget/})).toBeDisabled();
  await page.getByLabel("Assumed provider rate").fill("1.10");
  await page.getByLabel("Total billable GPU-hours").fill("8");
  await expect(page.getByText("$8.80", {exact:true})).toBeVisible();
  await page.getByLabel("Assumed transaction virtual size").fill("1321");
  await expect(page.getByText("5,284 sats", {exact:true})).toBeVisible();
  unavailable = true;
  await page.getByRole("button", {name: "Refresh MARA rates"}).click();
  await expect(page.getByRole("alert")).toContainText("MARA rates unavailable");
  await expect(page.getByText("5,284 sats", {exact:true})).toHaveCount(0);
  await page.getByLabel("Assumed provider rate").fill("-1");
  await expect(page.getByText("$8.80", {exact:true})).toHaveCount(0);
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path:"test-results/qsb-costs-mobile.png",fullPage:true});
});
