import {fingerprint} from '../../outputs/qsb-vault/src/lib/provenance';
import {createHash} from 'node:crypto';
import {isDeepStrictEqual} from 'node:util';
import {validateConfig,type Config} from '../yukon-common-operational-transport-20260923/transport';
import type {CensusStore} from '../yukon-common-census-fence-20260923/census-store';
import type {EvidenceReaders,ReapedEvidence} from '../yukon-signing-export-20260923/publication';
import {retained} from '../yukon-retained-endpoint-retirement-20260923/retained';
const hash=(v:any)=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
const same=(a:any,b:any)=>isDeepStrictEqual(a,b);
const stages=['pin','subset'] as const;
export type Stage=typeof stages[number];
/** Application-owned functions only. No public request may choose an actuator or observation. */
export type DeletionIO={inspect:(stage:Stage)=>Promise<any>;health:(stage:Stage)=>Promise<{queued:0;inProgress:0}>;remove204:(stage:Stage)=>Promise<void>};
export type LiveDrain=(store:CensusStore,shutdown:any)=>Promise<any>;
function need(x:any,m:string):asserts x{if(!x)throw Error(m);}
function os(q:ReapedEvidence,c:Config,s:any){need(q.runPk==='SUPERVISION#'+c.blueprint.runId&&q.configHash===hash(c.blueprint)&&q.snapshotHash===s.snapshotHash&&q.durableOwnerVersion===s.durableOwnerVersion&&q.processesReaped&&q.cpuContainersAbsent&&q.registeredRecoveryReaped&&q.transportMode==='operational','Exact stopped OS authority required');}
function endpoint(v:any,e:any){need(v&&v.id===e.id&&v.createdAt===e.createdAt&&v.image===e.image&&v.type==='QUEUE'&&v.workers?.min===0&&v.workers?.max===0,'Exact disabled endpoint required');}
function key(c:Config,s:any){return'ENDPOINT_RETIREMENT#'+hash({config:c,snapshot:s.snapshotHash});}
/** New durable namespace deliberately leaves the immutable Common shutdown census unchanged. */
export function retirement(store:CensusStore,input:Config,shutdownInput:any,readQuiescence:()=>Promise<ReapedEvidence>){
 const c=validateConfig(input),s=structuredClone(shutdownInput),pk=key(c,s);
 async function state(){const a=await retained(store,c,s),q=structuredClone(await readQuiescence());os(q,c,s);const b=await retained(store,c,s);need(same(a,b),'Late stopped writer');return{inventory:{inventoryHash:a.inventoryHash,markerHash:a.markerHash,knownHash:hash(a.known)},os:q};}
 async function plan(){const p:any=await store.get(pk,'PLAN');need(p&&p.version===1&&p.format==='qsb-endpoint-retirement-plan-v1'&&p.configHash===hash(c)&&p.snapshotHash===s.snapshotHash&&same(p.config,c),'Exact retained retirement plan required');const now=await state();need(same(now,p.bound),'Stopped inventory/OS authority changed');return p;}
 async function fences(){const keys=[['SUPERVISION#'+c.blueprint.runId,'OWNER'],['SUPERVISION#'+c.blueprint.runId,'SHUTDOWN'],...s.snapshot.scopes.map((x:any)=>[x.pk,'SCOPE'])];const rows=await Promise.all(keys.map(([p,k])=>store.get(p,k)));need(rows.every(Boolean),'Missing stopped fences');return rows.map(row=>({row:row!,expected:row!.version}));}
 return{
  /** Called before either deletion. A missing receipt can never be recovered from 404 alone. */
  async prepare(observe:LiveDrain){if(await store.get(pk,'PLAN'))return await plan();const before=await state(),d=structuredClone(await observe(store,structuredClone(s)));need(d.format==='qsb-common-final-drain-v1'&&d.configHash===hash(c)&&d.censusHash===s.snapshotHash&&d.inventoryHash===before.inventory.inventoryHash&&d.markerHash===before.inventory.markerHash&&hash(d.knownTerminals)===before.inventory.knownHash&&d.endpoints.length===2,'Exact live final drain required');for(const k of stages){const e=c[k];need(d.endpoints.some((x:any)=>x.stage===k&&x.id===e.id&&x.createdAt===e.createdAt&&x.image===e.image&&x.workersMin===0&&x.workersMax===0&&x.queued===0&&x.inProgress===0),'Live resource binding differs');}const f=await fences();need(same(before,await state()),'Late writer while preparing deletion');const row={pk,sk:'PLAN',version:1,format:'qsb-endpoint-retirement-plan-v1',config:c,configHash:hash(c),snapshotHash:s.snapshotHash,bound:before,drainHash:hash(d),drainEndpoints:d.endpoints,preparedAtMs:Date.now()};await store.atomicPut([{row},...f]);return row;},
  /** One create-once claim, one DELETE. Unknown acknowledgements remain held, never retried here. */
  async delete(stage:Stage,io:DeletionIO){need(stages.includes(stage),'Unknown stage');const p=await plan(),sk='DELETE#'+stage,old=await store.get(pk,sk),done=await store.get(pk,'RECEIPT#'+stage);if(done){need(old&&done.planHash===fingerprint(p)&&done.intentHash===fingerprint(old)&&done.stage===stage&&done.acknowledgedStatus===204&&done.absenceConfirmed===true,'Invalid deletion receipt');return done;}need(!old,'Deletion outcome unresolved; no automatic retry');endpoint(await io.inspect(stage),c[stage]);need(same(await io.health(stage),{queued:0,inProgress:0}),'Jobs not drained');const f=await fences();need(same(p,await plan()),'Plan changed before deletion claim');const intent={pk,sk,version:1,stage,planHash:fingerprint(p),resource:structuredClone(c[stage]),claimedAtMs:Date.now()};await store.atomicPut([{row:intent},...f]);
   // After the durable claim, every exception is conservatively an unresolved deletion.
   endpoint(await io.inspect(stage),c[stage]);need(same(await io.health(stage),{queued:0,inProgress:0}),'Late provider work');need(same(p,await plan()),'Stopped authority changed before DELETE');await io.remove204(stage);need(await io.inspect(stage)===null,'Absence not independently confirmed');const finishFences=await fences();need(same(p,await plan()),'Stopped authority changed after DELETE');const receipt={pk,sk:'RECEIPT#'+stage,version:1,format:'qsb-owned-endpoint-deleted-v1',stage,resource:structuredClone(c[stage]),planHash:fingerprint(p),intentHash:fingerprint(intent),acknowledgedStatus:204,absenceConfirmed:true,completedAtMs:Date.now()};await store.atomicPut([{row:receipt},{row:intent,expected:intent.version},...finishFences]);return receipt;
  },
  /** Historical absence is accepted ONLY with this exact acknowledged-deletion authority and live terminal census. */
  async readFinalDrain(expected:any){const p=await plan();need(expected.runPk==='SUPERVISION#'+c.blueprint.runId&&expected.configHash===hash(c.blueprint)&&expected.snapshotHash===s.snapshotHash,'Drain request differs');for(const k of stages){const i:any=await store.get(pk,'DELETE#'+k),r:any=await store.get(pk,'RECEIPT#'+k);need(i&&r&&i.version===1&&r.version===1&&i.stage===k&&r.stage===k&&r.format==='qsb-owned-endpoint-deleted-v1'&&same(i.resource,c[k])&&same(r.resource,c[k])&&i.planHash===fingerprint(p)&&r.planHash===fingerprint(p)&&r.intentHash===fingerprint(i)&&r.acknowledgedStatus===204&&r.absenceConfirmed===true&&Number.isSafeInteger(r.completedAtMs)&&r.completedAtMs>=i.claimedAtMs,'Exact acknowledged deletion missing');}const current=await retained(store,c,s);need(hash(current.known)===p.bound.inventory.knownHash&&same(p,await plan()),'Late writer after deleted-resource evidence');return{format:'qsb-final-provider-drain-v1' as const,runPk:expected.runPk,configHash:expected.configHash,snapshotHash:s.snapshotHash,retirementAuthority:{format:'qsb-retained-resource-authority-v1',planPk:pk,planHash:fingerprint(p)},observedAtMs:Date.now(),endpoints:stages.map(k=>({id:c[k].id,workersMin:0 as const,workersMax:0 as const,inQueue:0 as const,inProgress:0 as const})),providers:current.known.map((x:any)=>({scope:x.scope.slice(11),intent:x.intent,id:x.provider,status:x.status}))};},
 };
}
/** Explicit trusted join; never an automatic fallback when live health returns 404. */
export function withRetiredEndpoints(existing:EvidenceReaders,retired:ReturnType<typeof retirement>):EvidenceReaders{return{readQuiescence:existing.readQuiescence,readFinalDrain:retired.readFinalDrain};}
