"""Native validation/install driver for a fresh, explicitly isolated SSM host; no provider credentials."""
import hashlib,json,os,shutil,subprocess,sys,tarfile,tempfile
from pathlib import Path
import boto3

def run(args):
    r=subprocess.run(args,capture_output=True,text=True,timeout=120)
    if r.returncode:raise RuntimeError('Validation command failed: '+args[0]+' code '+str(r.returncode))
    return r.stdout

def unpack(archive,dest):
    dest.mkdir(parents=True,exist_ok=False)
    with tarfile.open(archive,'r:gz') as t:
        for m in t.getmembers():
            if not m.isfile() and not m.isdir():raise ValueError('Unexpected archive member')
            if Path(m.name).is_absolute() or '..' in Path(m.name).parts:raise ValueError('Unsafe archive member')
        t.extractall(dest,filter='data')

def main():
    if os.geteuid()!=0 or os.uname().machine!='x86_64' or len(sys.argv)!=7:raise ValueError('Isolated x86_64 host and exact artifact hashes required')
    bucket,runtime_hash,dispatcher_hash,tests_hash,cpu_hash,commit=sys.argv[1:]
    if Path('/source').exists() or Path('/opt/qsb/dispatcher').exists():raise ValueError('Fresh validation host required')
    s3=boto3.client('s3',region_name='eu-west-1');digests={};Path('/input').mkdir(exist_ok=False)
    for name,sha,target in [('runtime',runtime_hash,'/input/runtime'),('dispatcher',dispatcher_hash,'/input/dispatcher'),('tests',tests_hash,'/tests')]:
        dest=Path('/input/'+name+'.tar.gz');s3.download_file(bucket,name+'.tar.gz',str(dest))
        if hashlib.sha256(dest.read_bytes()).hexdigest()!=sha:raise ValueError('Artifact archive differs')
        unpack(dest,Path(target));digests[name]=sha
    cpu=Path('/input/cpu-images.tar.gz');s3.download_file(bucket,'cpu-images.tar.gz',str(cpu))
    h=hashlib.sha256()
    with cpu.open('rb') as f:
        for chunk in iter(lambda:f.read(1024*1024),b''):h.update(chunk)
    if h.hexdigest()!=cpu_hash:raise ValueError('CPU archive differs')
    run(['docker','load','--input',str(cpu)])
    expected=['sha256:06bd9bc5f97212a460aa7605367882ee434d219bd8d8680f90a70a4d2ad718f1','sha256:2b6593d42253553344af6a3a451c121eb9ee94fed591dfc7fa0f15e616df2311']
    for image in expected:
        info=json.loads(run(['docker','image','inspect',image]))[0]
        if info['Id']!=image or info['Architecture']!='amd64':raise ValueError('CPU image identity differs')
    Path('/validation').mkdir(mode=0o700)
    # Dummy-only probe path is installed by linux-test.py before normal runtime installation.
    local=run(['/usr/local/bin/python','/tests/linux-test.py']);Path('/validation/linux-test.json').write_text(local)
    public_marker=Path('/validation/public-marker');public_marker.write_text('public-test-marker');public_marker.chmod(0o400)
    encrypted=Path('/etc/credstore.encrypted/qsb-validation-api');encrypted.parent.mkdir(mode=0o700,exist_ok=True)
    run(['systemd-creds','encrypt','--with-key=host','--name=runpod_api',str(public_marker),str(encrypted)])
    systemd=run(['systemd-run','--unit=qsb-credential-validation','--wait','--pipe','--property=LoadCredentialEncrypted=runpod_api:'+str(encrypted),'/usr/local/bin/python','/input/dispatcher/credential-exec.py'])
    if 'private FIFO transfer passed' not in systemd:raise ValueError('Credential service did not acknowledge private pipe')
    encrypted.unlink();public_marker.unlink()
    # Remove only the exact dummy probe generated by this driver's own test, never runtime state.
    probe=Path('/opt/qsb/dispatcher/dispatcher.cjs')
    if not probe.read_text().startswith("const fs=require('fs');"):raise ValueError('Unexpected test probe')
    probe.unlink();probe.parent.rmdir()
    watchdog=run(['/usr/local/bin/node','--test','/tests/watchdog.test.mjs']);Path('/validation/watchdog-tests.tap').write_text(watchdog)
    sys.path.insert(0,'/input/dispatcher');from install import install,verify
    runtime=Path('/input/runtime');dispatcher=Path('/input/dispatcher')
    rh=hashlib.sha256((runtime/'manifest.json').read_bytes()).hexdigest();dh=hashlib.sha256((dispatcher/'manifest.json').read_bytes()).hexdigest()
    receipt=install(runtime,dispatcher,Path('/'),rh,dh)
    for name in ['qsb-dispatch.service','qsb-watchdog@.service']:
        target=Path('/etc/systemd/system')/name
        if target.exists() or target.is_symlink():raise ValueError('Service already exists')
        shutil.copyfile(dispatcher/name,target);target.chmod(0o644)
    run(['systemctl','daemon-reload']);run(['systemd-analyze','verify','/etc/systemd/system/qsb-dispatch.service','/etc/systemd/system/qsb-watchdog@.service'])
    Path('/etc/qsb/host.json').write_text(json.dumps({'executionEnabled':False,'sourceCommit':commit,'region':'eu-west-1'}));Path('/etc/qsb/host.json').chmod(0o400)
    exact=run(['/usr/local/bin/python','/source/launch.py','check',rh])
    if 'Exact distribution verified' not in exact:raise ValueError('Sealed runtime check failed')
    verify(Path('/source'),rh,True);verify(Path('/opt/qsb/dispatcher'),dh)
    result={'sourceCommit':commit,'architecture':os.uname().machine,'installation':receipt,'archives':digests,'systemdEncryptedCredentialDummyPassed':True,'linuxChecks':json.loads(local),'watchdogChecks':7,'providerCalls':0,'realCredentials':False,'executionEnabled':False,'systemdServicesStarted':False,'runtimeImagesPreloaded':True,'cpuArchive':cpu_hash}
    Path('/validation/result.json').write_text(json.dumps(result,indent=2));print(json.dumps(result))
if __name__=='__main__':
    try:main()
    except Exception as e:
        print('Native installation/validation failed: '+str(e),file=sys.stderr);sys.exit(2)
