import {validateLineage} from './lineage';
import {isDeepStrictEqual} from 'node:util';
import {fingerprint} from '../../outputs/qsb-vault/src/lib/provenance';
import {readObservation} from '../yukon-indexed-controller-20260923/observations';
import {createHash} from 'node:crypto';import type {Row} from '../../outputs/qsb-vault/server/store';import type {CensusStore} from './census-store';import type {Blueprint} from './common';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
/** Durable readiness snapshot only; OS reap and provider drain are separate supervisor facts. */
export async function commonCensus(store:CensusStore,b:Blueprint,configHash:string){
 const run='SUPERVISION#'+b.runId,first=await store.get(run,'OWNER');if(!first||first.network!==b.network||first.configHash!==configHash||first.owner!==b.pin.owner||first.revision!==b.pin.revision||first.parent!==b.pin.parent||first.status!=='dispatch_stopped'||first.activeOperation!==null)throw Error('Active or unstopped owner');
 const p=await store.get('VALIDATION#'+b.pin.parent,'SCOPE'),c=await store.get('VALIDATION#'+b.subset.scope,'SCOPE');if(!p)throw Error('Missing owned parent');const scopes=[p,...(c?[c]:[])];
 for(const r of scopes)if(r.network!==b.network||r.identitySchema!=='provider-index-v1'||r.owner!==b.pin.owner||![b.pin.revision,b.pin.revision+1].includes(r.revision as number)||r.endpoint!==(r.pk===p.pk?b.pin.endpoint:b.subset.endpoint)||r.supervisedRun!==run||r.supervisedConfigHash!==configHash||r.dispatchClosed!==true||r.dispatchClosedBy!==run||r.identityConflict||!r.stopTransition)throw Error('Unclosed scope');
 if(c&&(p.childScope!==b.subset.scope||c.parentScope!==b.pin.parent||p.pinReceiptHash!==c.pinReceiptHash))throw Error('Reciprocal scope differs');
 const rows=await store.all(run),by=new Map(rows.map(r=>[r.sk,r]));if(by.size!==rows.length)throw Error('Duplicate census key');
 const owner=by.get('OWNER');if(!owner||JSON.stringify(owner)!==JSON.stringify(first))throw Error('Owner changed during census');
 await validateLineage(store,owner,run);const lineage=owner.adoption as any;if(lineage){const old=await store.get(lineage.predecessor,'OWNER');if(lineage.format!=='qsb-settled-adoption-v1'||!old||old.status!=='superseded'||old.successor!==run||old.version!==lineage.predecessorOwnerVersion||old.configHash!==lineage.predecessorConfigHash)throw Error('Continuation lineage changed');}

 for(const r of rows){if(!Number.isSafeInteger(r.version)||r.version<1||r.expiresAt!==undefined)throw Error('Invalid durable census row');
  if(r.sk.startsWith('ADOPTION_MANIFEST#')){if(!(owner.adoption||owner.contextCycle)||r.configHash!==configHash||r.format!=='qsb-adoption-requests-v1')throw Error('Foreign adoption manifest');continue;}
  if(r.sk==='OWNER')continue;if(r.sk==='SHUTDOWN'){if(r.configHash!==configHash)throw Error('Foreign shutdown receipt');continue;}
  if(r.sk.startsWith('OPERATION#')){if(r.configHash!==configHash||!['completed','accounted_not_sent'].includes(r.status as string))throw Error('Unresolved operation');if(r.status==='accounted_not_sent'&&!by.has(r.notSentReceipt as string))throw Error('Missing no-send operation receipt');}
  else if(r.sk.startsWith('CPU#')){if(r.configHash!==configHash||r.status!=='completed'||typeof r.entry!=='string'||typeof r.receipt!=='string'||!by.has(r.operationKey as string))throw Error('Unresolved CPU resource');const e=JSON.parse(r.entry),c=JSON.parse(r.receipt);if(e.runtimeOperation!==r.kind||e.scopeBinding?.network!==b.network||e.scopeBinding?.runPk!==run||e.scopeBinding?.configHash!==configHash||e.scopeBinding?.operationKey!==r.operationKey||c.containerAbsent!==true||c.clientReaped!==true||Object.keys(e).some(k=>JSON.stringify(e[k])!==JSON.stringify(c[k])))throw Error('CPU cleanup binding differs');}
  else if(r.sk.startsWith('REQUEST#')){if(r.configHash!==configHash||r.owner!==b.pin.owner||r.revision!==b.pin.revision||!['resolved','not_sent'].includes(r.status as string))throw Error('Unknown or pending transport');if(r.status==='resolved'&&typeof r.providerId!=='string')throw Error('Resolved request has no ID');if(r.status==='not_sent'){const n=by.get('NOT_SENT#'+r.sk);if(!n||n.format!=='qsb-common-not-sent-v1'||n.configHash!==configHash||n.knownNoSend!==true||n.intent!==r.intent||r.providerId!==undefined)throw Error('Unreconciled no-send request');}}
  else if(r.sk==='RECOVERY_CONTROL'){if(r.active!==null)throw Error('Recovery process active');}
  else if(r.sk.startsWith('RECOVERY#')){if(!['completed_reaped','aborted_reaped'].includes(r.status as string)||r.processExitProven!==true||r.postAuthorized!==false||r.originalEnrollmentHash!==configHash||r.owner!==b.pin.owner||r.revision!==b.pin.revision||!by.has('RECOVERY_CONTROL'))throw Error('Unreaped or foreign recovery');}
  else if(r.sk.startsWith('NOT_SENT#')){if(r.format!=='qsb-common-not-sent-v1'||r.configHash!==configHash||r.knownNoSend!==true||r.creditGranted!==false||typeof r.writerHash!=='string'||!/^[a-f0-9]{64}$/.test(r.writerHash)||!by.has(r.operationKey as string))throw Error('Foreign no-send receipt');}
  else if(r.sk.startsWith('RECEIPT_IMPORT#')){if(r.configHash!==configHash||r.owner!==b.pin.owner||r.revision!==b.pin.revision||r.creditGranted!==false)throw Error('Foreign import receipt');}
  else throw Error('Unknown census row '+r.sk);
 }
 const requestBindings:any[]=[],providerStatuses:any[]=[];let globalClaims:Row[]|undefined;
 for(const q of rows.filter(r=>r.sk.startsWith('REQUEST#'))){
  const inherited=q.inherited as any;if(inherited){if(!lineage||inherited.runPk!==lineage.predecessor||inherited.requestKey!==q.sk)throw Error('Inherited request provenance differs');const original=await store.get(inherited.runPk,q.sk);if(!original||fingerprint(original)!==inherited.requestHash||original.configHash!==lineage.predecessorConfigHash||original.status!=='resolved'||!isDeepStrictEqual({...original,pk:q.pk,version:1,configHash,inherited},q))throw Error('Inherited terminal request changed');}

  if(!['pinning','round1','round2'].includes(q.stage as string))throw Error('Unknown request stage');
  const scope=q.stage==='pinning'?b.pin.parent:b.subset.scope,pk='VALIDATION#'+scope;
  if(q.sk!=='REQUEST#'+hash(pk+':'+q.intent)||(q.stage==='pinning'?q.scope!==undefined:!String(q.intent).startsWith('RANGE#'+q.stage+':'))||q.parent!==b.pin.parent||(q.stage!=='pinning'&&q.scope!==b.subset.scope)||(!inherited&&q.endpoint!==(q.stage==='pinning'?b.pin.endpoint:b.subset.endpoint))||typeof q.intent!=='string')throw Error('Request scope binding differs');
  const [intent,index,journals]=await Promise.all([store.get(pk,q.intent),store.get(pk,'IDENTITY#'+q.intent),store.list(pk,'PROVIDER_OBS#'+q.intent+':')]);
  if(!intent||!index||intent.owner!==b.pin.owner||intent.revision!==b.pin.revision||intent.identityConflict||index.schema!=='provider-index-v1'||index.owner!==b.pin.owner||index.revision!==b.pin.revision||index.intent!==q.intent||index.ambiguous)throw Error('Request identity inventory differs');
  let claim:Row|undefined;if(q.status==='resolved'){claim=await store.get('VALIDATION#YUKON_PROVIDER_IDS',hash(q.providerId as string));if(!claim||claim.provider!==q.providerId||claim.scope!==scope||claim.intent!==q.intent)throw Error('Global provider claim differs');if(intent.provider!==q.providerId||index.count!==1||index.first!==q.providerId||journals.length!==1||journals[0].provider!==q.providerId||journals[0].schema!=='provider-index-v1'||journals[0].owner!==b.pin.owner||journals[0].revision!==b.pin.revision||journals[0].intent!==q.intent||journals[0].sk!=='PROVIDER_OBS#'+q.intent+':'+hash(q.providerId as string))throw Error('Resolved ID not uniquely indexed');}
  else{if(!globalClaims)globalClaims=(await Promise.all('0123456789abcdef'.split('').map(prefix=>store.list('VALIDATION#YUKON_PROVIDER_IDS',prefix)))).flat();const n=by.get('NOT_SENT#'+q.sk)!;if(intent.state!=='uncertain'||intent.provider!==undefined||index.count!==0||index.first!==undefined||journals.length||globalClaims.some(r=>r.scope===scope&&r.intent===q.intent)||n.frozenHash!==hash(intent.frozen as string)||n.owner!==b.pin.owner||n.revision!==b.pin.revision||n.scope!==scope)throw Error('Late identity invalidates no-send receipt');}
  let terminal:any=intent.terminal;if(!terminal&&intent.observation)terminal=await readObservation(store,intent);const terminalKnown=q.status==='resolved'&&terminal?.id===q.providerId&&['COMPLETED','FAILED','CANCELLED','TIMED_OUT'].includes(terminal.status);if(q.status==='resolved')providerStatuses.push({scope,intent:intent.sk,provider:q.providerId,status:terminalKnown?terminal.status:'UNKNOWN',terminalKnown});requestBindings.push({request:q.sk,intent,index,journals,claim:claim??null});
 }
 for(const scope of scopes){const prefix=scope.pk===p.pk?'PIN#':'RANGE#';for(const intent of await store.list(scope.pk,prefix)){if(intent.owner!==b.pin.owner||intent.revision!==b.pin.revision)throw Error('Unowned intent census');if((intent.provider!==undefined||intent.state==='uncertain')&&!requestBindings.some(x=>x.intent.pk===intent.pk&&x.intent.sk===intent.sk))throw Error('Unregistered transport intent');}}
 const snapshot={format:'qsb-common-census-v1',runPk:run,configHash,ownerVersion:owner.version,requestBindings,providerStatuses,durableProviderIntentsTerminal:providerStatuses.every(x=>x.terminalKnown),rows:rows.filter(r=>r.sk!=='SHUTDOWN').sort((a,b)=>a.sk.localeCompare(b.sk)),scopes,providerTerminalProven:false,processExitProven:false,sealEligible:false};const snapshotHash=hash(JSON.stringify(snapshot));
 const previous=by.get('SHUTDOWN'),control=by.get('RECOVERY_CONTROL');
 await store.atomicPut([{row:{...owner,version:owner.version+1},expected:owner.version},...scopes.map(r=>({row:{...r,version:r.version+1},expected:r.version})),...(control?[{row:{...control,version:control.version+1},expected:control.version}]:[]),{row:{pk:run,sk:'SHUTDOWN',version:previous?previous.version+1:1,configHash,snapshotHash,ownerVersion:owner.version+1,providerTerminalProven:false,processExitProven:false,sealEligible:false},...(previous?{expected:previous.version}:{})}]);
 return {snapshot,snapshotHash,durableOwnerVersion:owner.version+1,sealEligible:false};
}
