import {isDeepStrictEqual as eq} from 'node:util';import {createHash} from 'node:crypto';
import {fingerprint} from '../../outputs/qsb-vault/src/lib/provenance';
import type {CensusStore} from './census-store';import type {Blueprint} from './common';
import type {EvidenceReaders} from '../yukon-signing-export-20260923/publication';
import {prepareNextContext,retirementFences} from '../yukon-context-cycle-20260923/cycle';
import {stageRequestManifest} from './request-manifest';import {validateLineage} from './lineage';
const hash=(v:any)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');function need(v:any,m:string):asserts v{if(!v)throw Error(m);}
export async function adoptExhaustedContext(store:CensusStore,old:Blueprint,next:Blueprint,shutdown:any,readers:EvidenceReaders){
 old=structuredClone(old);next=structuredClone(next);shutdown=structuredClone(shutdown);const oldRun='SUPERVISION#'+old.runId,run='SUPERVISION#'+next.runId,oldHash=hash(old),configHash=hash(next),snap=shutdown.snapshot;
 need(['regtest','mainnet'].includes(old.network)&&old.network===next.network,'Context cycle network differs');
 need(oldRun!==run&&old.pin.owner===next.pin.owner&&old.pin.revision===next.pin.revision&&next.pin.owner===next.subset.owner&&next.pin.revision===next.subset.revision&&next.pin.parent===next.subset.parent&&new Set([old.pin.parent,old.subset.scope,next.pin.parent,next.subset.scope]).size===4,'New context identity required');
 need(snap?.runPk===oldRun&&snap.configHash===oldHash&&hash(snap)===shutdown.snapshotHash&&snap.durableProviderIntentsTerminal===true,'Unsettled source census');
 const o=await store.get(oldRun,'OWNER'),marker=await store.get(oldRun,'SHUTDOWN');need(o&&o.network===old.network&&marker&&o.status==='dispatch_stopped'&&o.lifecycle==='subset'&&o.activeOperation===null&&o.version===shutdown.durableOwnerVersion&&marker.snapshotHash===shutdown.snapshotHash&&marker.ownerVersion===o.version,'Stopped predecessor differs');
 need(!await store.get(run,'OWNER')&&!await store.get('VALIDATION#'+next.pin.parent,'SCOPE')&&!await store.get('VALIDATION#'+next.subset.scope,'SCOPE'),'Successor already exists');
 const ancestry=await validateLineage(store,o,oldRun),p=await store.get('VALIDATION#'+old.pin.parent,'SCOPE'),c=await store.get('VALIDATION#'+old.subset.scope,'SCOPE');need(p&&c&&snap.scopes.length===2,'Missing predecessor context');
 for(const s of [p,c]){const prior=snap.scopes.find((r:any)=>r.pk===s.pk);need(s.network===old.network,'Context scope network differs');need(prior&&s.network===old.network&&eq(s,{...prior,version:prior.version+1})&&s.phase==='paused'&&s.dispatchClosed===true&&!s.identityConflict,'Changed predecessor scope');}
 need((p.stopTransition as any)?.fromPhase==='subset_running'&&(c.stopTransition as any)?.fromPhase==='searching','Not stopped exhaustion');
 for(const row of snap.rows){need(eq(await store.get(oldRun,row.sk),row.sk==='OWNER'?o:row),'Changed predecessor census row');if(row.sk.startsWith('OPERATION#'))need(row.status==='completed','Unresolved operation');if(row.sk.startsWith('CPU#'))need(row.status==='completed','Unresolved CPU');if(row.sk.startsWith('REQUEST#'))need(row.status==='resolved','Unknown/no-send');if(row.sk.startsWith('RECOVERY'))throw Error('Recovery requires explicit context review');}
 const expected={runPk:oldRun,configHash:oldHash,snapshotHash:shutdown.snapshotHash},q=await readers.readQuiescence(),d=await readers.readFinalDrain(expected);
 need(q.runPk===oldRun&&q.configHash===oldHash&&q.snapshotHash===shutdown.snapshotHash&&q.durableOwnerVersion===o.version&&q.processesReaped&&q.cpuContainersAbsent&&q.registeredRecoveryReaped&&q.transportMode==='operational','Unreaped predecessor');
 need(d.runPk===oldRun&&d.configHash===oldHash&&d.snapshotHash===shutdown.snapshotHash&&d.endpoints.length===2&&[old.pin.endpoint,old.subset.endpoint].every(id=>d.endpoints.some(e=>e.id===id&&e.workersMin===0&&e.workersMax===0&&e.inQueue===0&&e.inProgress===0)),'Providers not disabled/drained');
 need(d.providers.length===snap.providerStatuses.length&&snap.providerStatuses.every((v:any)=>v.terminalKnown&&d.providers.some(e=>e.scope===v.scope&&e.intent===v.intent&&e.id===v.provider&&e.status===v.status)),'Terminal inventory differs');
 for(const [s,b] of [[p,next.pin],[c,next.subset]] as const){const previous=s.budget as any;need(Number.isSafeInteger(b.maxSubmissions)&&b.maxSubmissions>=previous.maxSubmissions&&b.maxSubmissions>=previous.claimed&&Number.isSafeInteger(b.submissionCutoffMs)&&b.submissionCutoffMs>Date.now()&&b.submissionCutoffMs<=b.deadlineMs&&b.deadlineMs<=Date.now()+1800000&&!['historical-proof-disabled-a','historical-proof-disabled-b'].includes(b.endpoint),'Explicit cumulative budget required');}
 need(eq(ancestry,await validateLineage(store,o,oldRun)),'Ancestor changed');
 // Eligibility primitive sees semantic pre-stop phases; all writes still CAS actual captured versions.
 const virtual:CensusStore={get:async(pk,sk)=>{const r=await store.get(pk,sk);if(!r||sk!=='SCOPE'&&sk!=='OWNER')return r;if(pk===p.pk&&sk==='SCOPE')return{...r,phase:'subset_running'};if(pk===c.pk&&sk==='SCOPE')return{...r,phase:'searching'};if(pk===oldRun&&sk==='OWNER')return{...r,status:'owned'};return r;},put:store.put.bind(store),delete:store.delete.bind(store),list:store.list.bind(store),all:store.all.bind(store),atomicPut:store.atomicPut.bind(store)};
 const binding={parent:old.pin.parent,child:old.subset.scope,nextParent:next.pin.parent,runPk:oldRun,owner:old.pin.owner,revision:old.pin.revision,configHash:oldHash};
 const prepared=await prepareNextContext(virtual,binding,async()=>({format:'qsb-context-retirement-proof-v1',binding,parentVersion:p.version,childVersion:c.version,ownerVersion:o.version,writersSettled:true,dispatchClosed:true,observedAtMs:Date.now(),endpoints:d.endpoints.map(e=>({id:e.id,min:0,max:0,queued:0,inProgress:0}))}));
 const fences=await retirementFences(store,next.pin.parent),[rp,rc,ro,retired,inert]=fences;
 const hashes=Object.fromEntries(snap.rows.filter((r:any)=>r.sk.startsWith('REQUEST#')).map((r:any)=>[r.sk,fingerprint(r)])),manifest=await stageRequestManifest(store,run,configHash,oldRun,hashes);
 const restored={...inert,network:next.network,version:inert.version+1,phase:'pinning_searching',endpoint:next.pin.endpoint,dispatchAuthorized:false,supervisedRun:run,supervisedConfigHash:configHash,budget:{...(inert.budget as object),deadlineMs:next.pin.deadlineMs,submissionCutoffMs:next.pin.submissionCutoffMs,maxSubmissions:next.pin.maxSubmissions},inheritedSubsetBudget:{...(inert.inheritedSubsetBudget as object),deadlineMs:next.subset.deadlineMs,submissionCutoffMs:next.subset.submissionCutoffMs,maxSubmissions:next.subset.maxSubmissions}};
 const contextCycle={format:'qsb-context-cycle-adoption-v1',predecessor:oldRun,predecessorConfigHash:oldHash,predecessorOwnerVersion:ro.version+1,snapshotHash:shutdown.snapshotHash,quiescenceHash:fingerprint(q),drainHash:fingerprint(d),retirementHash:inert.retirementHash,scopeHashes:[{pk:rp.pk,hash:fingerprint(rp)},{pk:rc.pk,hash:fingerprint(rc)}],...manifest};
 await store.atomicPut([{row:{...ro,version:ro.version+1,status:'superseded',successor:run},expected:ro.version},{row:{...marker},expected:marker.version},...([rp,rc,retired] as any[]).map(row=>({row,expected:row.version})),{row:restored,expected:inert.version},{row:{pk:run,sk:'OWNER',version:1,network:next.network,configHash,parent:next.pin.parent,owner:next.pin.owner,revision:next.pin.revision,status:'owned',activeOperation:null,lifecycle:'pin',stage:'pinning',contextCycle}}]);
 return{runPk:run,pinResumeFloor:prepared.next.pinResumeFloor,contextCycle};
}
