import {fingerprint} from '../../outputs/qsb-vault/src/lib/provenance';import type {CensusStore} from './census-store';
/** Retained predecessor pointers are flat; no recursively serialized request growth. */
export async function validateLineage(store:CensusStore,owner:any,run:string){const seen=new Set<string>([run]),evidence:any[]=[];let current=owner,currentRun=run;
 while(current.adoption||current.contextCycle){const a=current.adoption??current.contextCycle;if(!['qsb-settled-adoption-v1','qsb-context-cycle-adoption-v1'].includes(a.format)||typeof a.predecessor!=='string'||seen.has(a.predecessor)||seen.size>256)throw Error('Invalid continuation lineage');seen.add(a.predecessor);const prior=await store.get(a.predecessor,'OWNER');if(!prior||prior.network!==current.network||prior.status!=='superseded'||prior.successor!==currentRun||prior.version!==a.predecessorOwnerVersion||prior.configHash!==a.predecessorConfigHash)throw Error('Predecessor ownership lineage differs');
  if(current.contextCycle){if(!Array.isArray(a.scopeHashes)||a.scopeHashes.length!==2)throw Error('Missing context scopes');for(const e of a.scopeHashes){const row=await store.get(e.pk,'SCOPE');if(!row||row.phase!=='context_retired'||row.identityConflict||fingerprint(row)!==e.hash)throw Error('Retired context changed');}const r=await store.get(a.predecessor,'CONTEXT_RETIREMENT');if(!r)throw Error('Missing context retirement');const {pk,sk,version,...body}=r;if(version!==1||fingerprint(body)!==a.retirementHash)throw Error('Retirement receipt changed');const marker=await store.get(a.predecessor,'SHUTDOWN');if(!marker||marker.snapshotHash!==a.snapshotHash)throw Error('Ancestor shutdown changed');}
  const chunks=await store.list(currentRun,'ADOPTION_MANIFEST#');if(chunks.length!==a.requestChunkCount)throw Error('Incomplete request manifest');const hashes:string[]=[],entries:[string,string][]=[];
  for(let i=0;i<chunks.length;i++){const c=chunks.find(r=>r.sk==='ADOPTION_MANIFEST#'+i);if(!c||c.version!==1||c.format!=='qsb-adoption-requests-v1'||c.configHash!==current.configHash||c.predecessor!==a.predecessor||c.chunk!==i||!Array.isArray(c.entries)||c.entries.length>1000||fingerprint(c.entries)!==c.digest)throw Error('Invalid request manifest chunk');hashes.push(c.digest as string);entries.push(...c.entries as [string,string][]);}
  if(entries.length!==a.requestCount||new Set(entries.map(([k])=>k)).size!==entries.length||fingerprint(hashes)!==a.requestManifestHash)throw Error('Request manifest count/hash differs');
  const retained=await store.list(a.predecessor,'REQUEST#');if(retained.length!==entries.length)throw Error('Predecessor request inventory changed');const by=new Map(retained.map(r=>[r.sk,r]));
  for(const [key,expected]of entries){const r=by.get(key);if(!r||r.status!=='resolved'||fingerprint(r)!==expected)throw Error('Predecessor terminal provenance changed');}
  evidence.push({owner:prior,requestManifestHash:a.requestManifestHash});current=prior;currentRun=a.predecessor;
 }return {hash:fingerprint(evidence),generations:evidence.length};}
