/** CPU-free final publication. Dependencies are fixed trusted evidence readers, never uploaded receipts. */
import {createHash} from 'node:crypto';
import type {Row} from '../../outputs/qsb-vault/server/store';
import type {CensusStore} from './census-store';import type {Blueprint} from './common';
import {fingerprint,canonical} from '../../outputs/qsb-vault/src/lib/provenance';
import {validateSolvedState} from './contract';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');const same=(a:any,b:any)=>canonical(a)===canonical(b);function need(x:any,msg:string):asserts x{if(!x)throw Error(msg);}
export type ReapedEvidence={format:'qsb-common-reaped-evidence-v1';runPk:string;configHash:string;snapshotHash:string;durableOwnerVersion:number;controllerHash:string;wrapperHash:string;journalHash:string;receiptHash:string;processesReaped:true;cpuContainersAbsent:true;registeredRecoveryReaped:true;transportMode:'operational'};
export type FinalDrain={format:'qsb-final-provider-drain-v1';runPk:string;configHash:string;snapshotHash:string;observedAtMs:number;endpoints:{id:string;workersMin:0;workersMax:0;inQueue:0;inProgress:0}[];providers:{scope:string;intent:string;id:string;status:'COMPLETED'|'FAILED'|'CANCELLED'|'TIMED_OUT'}[]};
export interface EvidenceReaders {readQuiescence:()=>Promise<ReapedEvidence>;readFinalDrain:(shutdown:any)=>Promise<FinalDrain>}
async function prepared(store:CensusStore,pk:string,id:string){const m=await store.get(pk,'EXPORT_PREP#'+id);need(m&&m.format==='qsb-mainnet-solved-preparation-record-v1'&&Number.isSafeInteger(m.chunkCount)&&Number(m.chunkCount)>0&&Number(m.chunkCount)<1000,'No complete export preparation');let text='';for(let i=0;i<Number(m.chunkCount);i++){const c=await store.get(pk,'EXPORT_PREP_CHUNK#'+id+':'+m.operationKey+':'+i);need(c&&typeof c.text==='string'&&hash(c.text)===c.sha256,'Incomplete preparation chunk');text+=c.text;}need(hash(text)===m.encodedHash,'Preparation digest differs');const value=JSON.parse(text);need(value.preparedHash===m.preparedHash&&fingerprint(value.prepared)===m.preparedHash&&value.requestId===id&&value.runPk===m.runPk&&value.configHash===m.configHash,'Preparation binding differs');return{manifest:m,value};}
function scopeFromPreparation(current:Row,source:Row,id:string,preparedVersion:number){
 const expected={...source,version:preparedVersion,signingPreparation:id};need(current.stopTransition&&same(Object.fromEntries(Object.entries(current).filter(([k])=>!['version','phase','dispatchClosed','dispatchClosedBy','stopTransition'].includes(k))),Object.fromEntries(Object.entries(expected).filter(([k])=>!['version','phase','dispatchClosed','dispatchClosedBy','stopTransition'].includes(k)))),'Solved context changed after preparation');const t=current.stopTransition as any;need(t.fromVersion===preparedVersion&&t.fromPhase===source.phase&&t.fromStage===source.stage&&current.phase==='paused'&&current.dispatchClosed===true,'Stop did not retain exact solved context');
}
async function inventory(store:CensusStore,p:Row,c:Row){const result:any[]=[];for(const [s,prefix]of [[p,'PIN#'],[c,'RANGE#']] as const)for(const row of (await store.list(s.pk,prefix)).sort((a,b)=>a.sk.localeCompare(b.sk))){const index=await store.get(s.pk,'IDENTITY#'+row.sk);if(row.state==='unsubmitted_retired'&&!row.provider){result.push({row,index});continue;}need(typeof row.provider==='string','Unresolved provider');const js=await store.list(s.pk,'PROVIDER_OBS#'+row.sk+':');need(js.length===1,'Conflicting provider inventory');result.push({row,index,journal:js[0],claim:await store.get('VALIDATION#YUKON_PROVIDER_IDS',hash(row.provider))});}return result;}
/** Create-only record; subsequent indexed writes revoke admission by scope/OWNER version mismatch. */
export async function publishSolvedState(store:CensusStore,b:Blueprint,requestId:string,readers:EvidenceReaders){
 b=structuredClone(b);need(b.network==='mainnet','Mainnet blueprint required');const run='SUPERVISION#'+b.runId,configHash=hash(JSON.stringify(b)),ppk='VALIDATION#'+b.pin.parent,cpk='VALIDATION#'+b.subset.scope;
 // Capture all writer fences BEFORE awaiting inventories or external evidence.
 const [p,c,o,shutdown,recovery]=await Promise.all([store.get(ppk,'SCOPE'),store.get(cpk,'SCOPE'),store.get(run,'OWNER'),store.get(run,'SHUTDOWN'),store.get(run,'RECOVERY_CONTROL')]);
 need(p&&c&&o&&shutdown&&o.status==='dispatch_stopped'&&o.activeOperation===null&&o.configHash===configHash&&shutdown.configHash===configHash&&shutdown.ownerVersion===o.version&&(!recovery||recovery.active===null),'No settled common shutdown');
 for(const s of [p,c])need(s.network==='mainnet'&&s.supervisedRun===run&&s.supervisedConfigHash===configHash&&s.identitySchema==='provider-index-v1'&&!s.identityConflict&&s.dispatchClosedBy===run,'Unbound/quarantined scope');
 const prep=await prepared(store,cpk,requestId),v=prep.value,x=v.prepared;
 need(v.runPk===run&&v.configHash===configHash&&x.receipt.bundleSha256===fingerprint(x.bundle)&&x.receipt.snapshotHash===fingerprint(x.snapshot),'Prepared bundle differs');
 scopeFromPreparation(p,x.snapshot.parent,requestId,Number(prep.manifest.parentPreparedVersion));scopeFromPreparation(c,x.snapshot.child,requestId,Number(prep.manifest.childPreparedVersion));
 need(same(await inventory(store,p,c),x.snapshot.inventories),'Identity/terminal inventory changed');
 const op=await store.get(run,v.operationKey);need(op&&op.status==='completed'&&op.kind==='signing-export-preparation'&&op.preparationHash===v.preparedHash,'Unaccounted preparation operation');
 const process=await readers.readQuiescence();need(process.format==='qsb-common-reaped-evidence-v1'&&process.runPk===run&&process.configHash===configHash&&process.snapshotHash===shutdown.snapshotHash&&process.durableOwnerVersion===o.version&&process.processesReaped===true&&process.cpuContainersAbsent===true&&process.registeredRecoveryReaped===true&&process.transportMode==='operational','Missing authoritative enrolled process quiescence');
 const drain=await readers.readFinalDrain({runPk:run,configHash,snapshotHash:shutdown.snapshotHash,ownerVersion:o.version});need(drain.format==='qsb-final-provider-drain-v1'&&drain.runPk===run&&drain.configHash===configHash&&drain.snapshotHash===shutdown.snapshotHash&&Number.isSafeInteger(drain.observedAtMs)&&Date.now()-drain.observedAtMs>=0&&Date.now()-drain.observedAtMs<60000,'Stale/unbound provider drain');
 const endpoints=[...new Set([p.endpoint,c.endpoint])];need(drain.endpoints.length===endpoints.length&&endpoints.every(id=>drain.endpoints.some(e=>e.id===id&&e.workersMin===0&&e.workersMax===0&&e.inQueue===0&&e.inProgress===0)),'Endpoints not disabled/drained');
 const ids=x.snapshot.inventories.filter((z:any)=>z.row.provider).map((z:any)=>({scope:z.row.pk.slice(11),intent:z.row.sk,id:z.row.provider,status:z.row.terminal.status}));need(ids.length===drain.providers.length&&ids.every((i:any)=>drain.providers.some(d=>same(d,i))),'Missing exact provider terminal evidence');
 const bundle=validateSolvedState(x.bundle);need(bundle.request.id===requestId,'Request differs');
 const record:Row={pk:cpk,sk:'PUBLIC_EXPORT#'+requestId,version:1,format:'qsb-mainnet-solved-record-v1',requestId,runPk:run,configHash,preparationHash:v.preparedHash,bundleSha256:fingerprint(bundle),bundle:JSON.stringify(bundle),provenance:JSON.stringify({solver:x.receipt,process,drain,snapshotHash:shutdown.snapshotHash}),parentVersion:p.version,childVersion:c.version,ownerVersion:o.version,shutdownVersion:shutdown.version,mainnetAuthorized:false};
 need(Buffer.byteLength(JSON.stringify(record))<350000,'Public export exceeds safe item bound');
 await store.atomicPut([{row:{...p},expected:p.version},{row:{...c},expected:c.version},{row:{...o},expected:o.version},{row:{...shutdown},expected:shutdown.version},...(recovery?[{row:{...recovery},expected:recovery.version}]:[]),{row:record}]);
 return {requestId,bundleSha256:record.bundleSha256,recordKey:{pk:record.pk,sk:record.sk},mainnetAuthorized:false};
}
/** Admission check before handing out/accepting a v1 file. It cannot prevent independent offline use of an old file. */
export async function admitCurrentSolvedState(store:CensusStore,b:Blueprint,requestId:string,readers:EvidenceReaders){
 b=structuredClone(b);need(b.network==='mainnet','Mainnet blueprint required');const run='SUPERVISION#'+b.runId,pk='VALIDATION#'+b.subset.scope,r=await store.get(pk,'PUBLIC_EXPORT#'+requestId);need(r&&r.format==='qsb-mainnet-solved-record-v1'&&r.runPk===run&&r.configHash===hash(JSON.stringify(b)),'No public export record');
 const [p,c,o,shutdown]=await Promise.all([store.get('VALIDATION#'+b.pin.parent,'SCOPE'),store.get(pk,'SCOPE'),store.get(run,'OWNER'),store.get(run,'SHUTDOWN')]);need(p&&c&&o&&shutdown&&p.version===r.parentVersion&&c.version===r.childVersion&&o.version===r.ownerVersion&&shutdown.version===r.shutdownVersion&&!p.identityConflict&&!c.identityConflict,'Export revoked by later durable evidence');
 const saved=JSON.parse(r.provenance as string),process=await readers.readQuiescence();need(same(process,saved.process),'Process enrollment evidence changed');const d=await readers.readFinalDrain({runPk:run,configHash:r.configHash,snapshotHash:shutdown.snapshotHash,ownerVersion:o.version,exportRecord:r});need(d.format==='qsb-final-provider-drain-v1'&&Array.isArray(d.providers)&&Array.isArray(d.endpoints)&&d.runPk===run&&d.configHash===r.configHash&&d.snapshotHash===shutdown.snapshotHash&&Date.now()-d.observedAtMs>=0&&Date.now()-d.observedAtMs<60000&&same(d.providers,saved.drain.providers)&&same(d.endpoints,saved.drain.endpoints),'Provider evidence no longer current');
 // Read-only acceptance is a momentary assertion; final caller must not separate this check from its intended action.
 need(same(await store.get(p.pk,'SCOPE'),p)&&same(await store.get(c.pk,'SCOPE'),c)&&same(await store.get(run,'OWNER'),o)&&same(await store.get(run,'SHUTDOWN'),shutdown)&&same(await store.get(pk,r.sk),r),'Export changed during admission');const bundle=validateSolvedState(JSON.parse(r.bundle as string));need(fingerprint(bundle)===r.bundleSha256,'Stored bundle digest differs');return{bundle,record:r,mainnetAuthorized:false};
}
