import type {CensusStore} from '../yukon-common-census-fence-20260923/census-store';import type {Blueprint} from '../yukon-signing-export-20260923/common';
import {createHash} from 'node:crypto';
const same=(a:any,b:any)=>JSON.stringify(a)===JSON.stringify(b);
/** Bounded read-only summary. Actual controller revalidates every action; this is not dispatch authorization. */
export async function status(store:CensusStore,b:Blueprint,drain:()=>Promise<any>){const run='SUPERVISION#'+b.runId,h=createHash('sha256').update(JSON.stringify(b)).digest('hex');const owner=await store.get(run,'OWNER'),p=await store.get('VALIDATION#'+b.pin.parent,'SCOPE'),c=await store.get('VALIDATION#'+b.subset.scope,'SCOPE');if(!owner||!p||owner.configHash!==h||owner.owner!==b.pin.owner||owner.revision!==b.pin.revision)throw Error('Status owner differs');
 const scope=(r:any)=>r?Object.fromEntries(['version','phase','stage','nextAttempt','pinResumeFloor','identityConflict','dispatchClosed','signingPreparation','budget'].filter(k=>r[k]!==undefined).map(k=>[k,r[k]]).concat([['solutions',Object.keys(r.solutions??{})]])):null;
 const inventory=async(r:any)=>{if(!r)return[];const rows=await store.list(r.pk,r.pk===p.pk?'PIN#':'RANGE#');if(rows.length>10000)throw Error('Status inventory oversized');return Promise.all(rows.map(async i=>{const index=await store.get(r.pk,'IDENTITY#'+i.sk);if(i.owner!==b.pin.owner||i.revision!==b.pin.revision||!index||index.owner!==i.owner||index.revision!==i.revision||index.intent!==i.sk)throw Error('Status inventory unbound');return{sk:i.sk,state:i.state,provider:i.provider??null,terminalStatus:(i.terminal as any)?.status??null,candidateVerified:i.state==='candidate'||i.state==='candidate_verified',identityConflict:i.identityConflict===true,index:{count:index.count,ambiguous:index.ambiguous===true}};}));};
 const pinIntents=await inventory(p),subsetIntents=await inventory(c);let parentDrain:any={ready:false,reason:'not-required'};
 if(p.phase==='pinning_draining'){try{const d=await drain();parentDrain={...d,ready:d.endpoint===b.pin.endpoint&&Date.now()-d.observedAtMs>=0&&Date.now()-d.observedAtMs<5000&&d.workersMin===0&&d.workersMax===0&&d.queued===0&&d.inProgress===0};}catch{parentDrain={ready:false,reason:'observation-unavailable'};}}
 if(!same(owner,await store.get(run,'OWNER'))||!same(p,await store.get(p.pk,'SCOPE'))||!same(c,await store.get('VALIDATION#'+b.subset.scope,'SCOPE')))throw Error('Status changed during read');
 const result={format:'qsb-common-driver-status-v1',owner:{status:owner.status,lifecycle:owner.lifecycle??null,activeOperation:owner.activeOperation??null},parent:scope(p),child:scope(c),pinIntents,subsetIntents,parentDrain,observedAtMs:Date.now()};if(Buffer.byteLength(JSON.stringify(result))>1500000)throw Error('Status result oversized');return result;
}
