// Generated by scripts/generate-solver-registry.mjs; do not edit.
import d0 from "./qsb-solver-aws-v0-1-0.json";
import d1 from "./qsb-solver-combined-aws-sm86-v0-2-0.json";
import d2 from "./qsb-solver-v0-1-0.json";
export default [d0, d1, d2] as unknown[];
